### ISSUE TITLE
How to use with jiti to make it compatible with vscode-uri

### ISSUE THREAD

**Issue by Miofly** [fi3ework/vite-plugin-checker#183]
### Describe the bug

0.4.9 run corret, but 0.5 more incorrect
![image](https://user-images.githubusercontent.com/42859910/199698309-f03e82c8-9643-4f80-80d7-b5c53dca8861.png)

### Reproduction

no

### Expected behavior

start error

### System Info

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (6) x64 Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
    Memory: 24.96 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.0.0 - /usr/local/opt/nvm/versions/node/v16.0.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.10.0 - /usr/local/opt/nvm/versions/node/v16.0.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Firefox: 99.0.1
    Safari: 12.1.2
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fi3ework** [comment]
@Miofly Could you give a re-production of how to use Vite & vite-plugin-checker & jiti together?

**Comment by fi3ework** [comment]
And thanks @Litarvan, this is properly a bug of jiti. If a re-production could be provided. I think it's easy to make a hack to compatible with jiti. Before 0.5.0, vite-plugin-checker only ships a CJS version. From 0.5.0, ESM and CJS version are both shipped and ESM is adopted by jiti IMO.

**Comment by Litarvan** [comment]
This is really strange, because it seems Nuxt is trying to load the ESM module in both a CJS and a ESM way. I've attached a reproduction of the bug itself in [the Jiti issue](https://github.com/unjs/jiti/issues/105).
It can also easily be reproduced by setting up a blank Nuxt 3 project, registering vite-plugin-checker, and starting the dev server.

In the meantime, I used a (dirty) workaround on my side [which I've described in my own issue](https://github.com/fi3ework/vite-plugin-checker/issues/197)
