### ISSUE TITLE
require(...).loadTsLib is not a function

### ISSUE THREAD

**Issue by eleven-net-cn** [fi3ework/vite-plugin-checker#222]
### Describe the bug

```zsh
TypeError [Error]: require(...).loadTsLib is not a function
     at /Users/xxx/node_modules/vite-plugin-checker/dist/cjs/checkers/vueTsc/typescript-vue-tsc/lib/tsc.js:3505:105
```

If vue-tsc@1.1.0 is used, the error above will occur.

It works fine when reverting to vue-tsc@1.0.24.

### Reproduction

vite-plugin-checker v0.5.5
vue-tsc v1.1.0

### Expected behavior

vite-plugin-checker may need some optimization changes.

### System Info

```shell
--
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by jelledv49** [comment]
Just encountered the same issue. Reverting to 1.0.24 indeed works

**Comment by johannschopplich** [comment]
Same issue here since vue-tsc v1.1.0.

**Comment by johnsoncodehk** [comment]
Just removing this line can fix: https://github.com/fi3ework/vite-plugin-checker/blob/f65aa71a1ac9ab8374085449503174be935658c6/packages/vite-plugin-checker/src/checkers/vueTsc/prepareVueTsc.ts#L81

@fi3ework Does vite-plugin-checker have to maintain this code by itself?

**Comment by fi3ework** [comment]
@johnsoncodehk Thanks for the help. I didn't know the usage clearly so I copied it from https://github.com/vuejs/language-tools/blob/master/packages/vue-tsc/bin/vue-tsc.js before. I'll remove this line soon and release a patch version.

I think for now vite-plugin-checker has to maintain by itself because the code to replace is not in a JSON or exported variable nowadays in `bin/vue-tsc.js` 👀. Do you think making the replacement operation exportable to other packages is a good idea?

**Comment by fi3ework** [comment]
I think there's also something broken in vue-tsc@^1.1.0(see https://github.com/vuejs/language-tools/issues/2403). Use older version before vite-plugin-checker and vue-tsc are all good after 1.1.0.

**Comment by johnsoncodehk** [comment]
> I think for now vite-plugin-checker has to maintain by itself because the code to replace is not in a JSON or exported variable nowadays in `bin/vue-tsc.js` 👀. Do you think making the replacement operation exportable to other packages is a good idea?

Yes, I will see how to do it.
