### ISSUE TITLE
[Vue warn]: Extraneous non-props attributes (ariaHidden)

### ISSUE THREAD

**Issue by MurphyCoder** [fi3ework/vite-plugin-checker#308]
### Describe the bug

I need help, I get the following warning with React 18 + VITE.
```
virtual:@vite-plugin-checker-runtime:1238 [Vue warn]: Extraneous non-props attributes (ariaHidden) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <App.ce base="/" overlayConfig= {initialIsOpen: false} ariaHidden=null >
```

![CleanShot 2024-03-13 at 16 40 08](https://github.com/fi3ework/vite-plugin-checker/assets/25988846/8f974f6b-7a4a-43d9-ba9e-49545a97f7f7)

### Reproduction

 React 18 + VITE.

### Expected behavior

 React 18 + VITE.

### System Info

```shell
React 18 + VITE.
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by gregtayl** [comment]
We're running into the same warning in v0.6.4.

It appears to be caused by the vite-checker-plugin overlay, which renders a visual overlay to the dom detailing any violations. The overlay component happens to be written in Vue, and appears to be responsible for raising these warnings. Disabling the overlay in your vite-config.ts makes the warning go away (but then you don't get the nice list of violations in the browser window).

![image](https://github.com/fi3ework/vite-plugin-checker/assets/5607078/51ac70b1-c3d9-4403-b134-68e1fb7e2e64)

**Comment by quicklikerabbit** [comment]
Can confirm the warnings disappear if the overlay is disabled. 
The warnings make reference to `App.ce`, perhaps thats this component in the runtime package? https://github.com/fi3ework/vite-plugin-checker/blob/main/packages/runtime/src/App.ce.vue

**Comment by troyschneringer** [comment]
I have the same problem when `initialIsOpen: false`.  If set to `true` or omitted then the warning does not appear.

**Comment by jhoermann** [comment]
Opened a PR https://github.com/fi3ework/vite-plugin-checker/pull/345 to resolve the issue now. Reproduces it locally and it removes the warning as expected @fi3ework if you want to have a look.
